### PR TITLE
feat(android): use new map api

### PR DESCRIPTION
**Pull request by m1ga**
* Use new Map Renderer (https://developers.google.com/maps/documentation/android-sdk/renderer)
* updated map-utils

> An upgraded map renderer is available as of version 18.0.0 of the Maps SDK for Android. This renderer brings many improvements, including support for Cloud-based maps styling. You can opt-in to try the new renderer before it becomes the default renderer for Android devices, through a progressive rollout starting in March 2022 at the earliest.

[ti.map-android-5.4.0.zip](https://github.com/appcelerator-modules/ti.map/files/8108987/ti.map-android-5.4.0.zip)

there are a lot of debug messages ` ProxyAndroidLoggerBackend: Too many Flogger logs received before configuration. Dropping old logs.`

### CODE REVIEW

**Comment by hansemannn** [comment]
Really cool! Is it stable already for you? I will update iOS as well!

**Comment by m1ga** [comment]
Yes, no problems in my app so far. Visual changes are not big that the users would see a difference, which is good :)

Screenshot_20211028-220748

**Comment by hansemannn** [comment]
We get looots of errors like these:
```
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
[ERROR] E/com.appc.myapp: Resource 7f12000e is a complex map type.
```

**Comment by m1ga** [comment]
not sure if that is related to the "map": 
https://stackoverflow.com/questions/52142289/resource-is-a-complex-map-type
that is from 2018 and they have that error too and one hint was a resource string.

**Comment by hansemannn** [comment]
Tracing it! `7f12000e` is used in `int style AppButtonAppearance 0x7f12000e`, so in the custom theme.

**Comment by m1ga** [comment]
@hansemannn nice :+1: Test version 393 runs without any issues :wink:

**Comment by hansemannn** [comment]
@m1ga Can you rebase? Happy to merge this soon

**Comment by m1ga** [comment]
@hansemannn how do I rebase or why do I need to?
Can't you just use the `rebase and merge` button? Or better the `squash and merge`?

**Comment by hansemannn** [comment]
Oh, I thought merging is blocked otherwise. We could merge here, but we should really get the CI working, so we can grab the artifacts from there.

**Comment by m1ga** [comment]
@hansemannn I've change to log in the initialization so it will only make a debug log when it is using the legacy map:
https://github.com/tidev/ti.map/pull/491/commits/f0874b411bf14e02099478b171a3e147904e75ca

It's debug log but still not needed for `latest` all the time

**Comment by hansemannn** [comment]
@m1ga The linter fails because of the imports in the `MapModule.java`, can you check these? After that, it should be ready to merge!

**Comment by m1ga** [comment]
@hansemannn done. Line length was the issue. I always forget that some modules have the `npm run format:andorid`. Local linter is happy now. It hits the fetch limit thats why the current build failed. Any way to trigger dangerJs again to remove the lint warning?

**Pull request merged**
